[package]
name = "dzn-rs"
description = "A library for dealing with DZN files used in the MiniZinc language."
version = "0.2.0"
edition = "2021"
authors = ["Maarten Flippo"]
license = "MIT"

[dependencies]
proptest = "1.4.0"
thiserror = "1.0.60"
winnow = "0.6.20"
